(() => {
  const section = document.querySelector('.experience-section');
  if (!section) return;
  const articles = [
    {number:'01',tag:'MÁY LẠNH',title:'Máy lạnh không lạnh: những nguyên nhân thường gặp',intro:'Máy vẫn chạy nhưng phòng lâu mát hoặc gió ra yếu? Hãy kiểm tra theo dấu hiệu trước khi nghĩ đến việc thay linh kiện.',link:'kinh-nghiem/may-lanh-khong-lanh.html'},
    {number:'02',tag:'MÁY LẠNH',title:'Máy lạnh chảy nước trong nhà: nên kiểm tra gì?',intro:'Nước nhỏ xuống tường hoặc sàn không phải lúc nào cũng chỉ do một nguyên nhân. Có thể bắt đầu từ đường thoát nước và tình trạng dàn lạnh.',link:'kinh-nghiem/may-lanh-chay-nuoc.html'},
    {number:'03',tag:'MÁY GIẶT',title:'Máy giặt không vắt: kiểm tra từ đâu?',intro:'Máy giặt cấp nước và giặt bình thường nhưng không vắt thường liên quan đến bước xả, khóa cửa, cảm biến hoặc hệ truyền động.',link:'kinh-nghiem/may-giat-khong-vat.html'},
    {number:'04',tag:'TỦ LẠNH',title:'Tủ lạnh không đông đá: những điều nên để ý',intro:'Ngăn đá yếu hoặc không đông có thể xuất hiện cùng nhiều dấu hiệu khác nhau. Việc kiểm tra cần dựa trên tình trạng thực tế của tủ.',link:'kinh-nghiem/tu-lanh-khong-dong-da.html'},
    {number:'05',tag:'MÁY NƯỚC NÓNG',title:'Máy nước nóng nhảy CB: khi nào nên dừng sử dụng?',intro:'Nhảy CB, rò điện hoặc có dấu hiệu bất thường liên quan đến điện là tình trạng cần ưu tiên an toàn trước khi nghĩ đến việc sửa nhanh.',link:'kinh-nghiem/may-nuoc-nong-nhay-cb.html'},
    {number:'06',tag:'LÒ VI SÓNG',title:'Lò vi sóng chạy nhưng không nóng: đừng tự mở máy',intro:'Lò vẫn quay và hoạt động nhưng thức ăn không nóng có thể liên quan đến nhóm linh kiện điều khiển hoặc gia nhiệt.',link:'kinh-nghiem/lo-vi-song-chay-khong-nong.html'}
  ];
  section.innerHTML = `<div class="section-heading experience-heading-v2"><p class="eyebrow-dark">KINH NGHIỆM SỬ DỤNG</p><h2 id="experience-title">Biết đúng cách, <span>đỡ tốn tiền</span></h2><p>Kiến thức thực tế về máy lạnh, máy giặt, tủ lạnh, máy nước nóng và lò vi sóng giúp bạn nhận biết dấu hiệu sớm, sử dụng an toàn và biết khi nào nên gọi thợ.</p></div><div class="experience-grid experience-grid-v2">${articles.map(article=>`<article class="experience-card experience-card-v2 reveal"><div class="experience-card-meta"><span>${article.number}</span><b>${article.tag}</b></div><h3>${article.title}</h3><p class="experience-intro">${article.intro}</p><a class="experience-link-btn" href="${article.link}">Đọc hướng dẫn <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`;
  const style = document.createElement('style');
  style.id = 'experience-seo-v2';
  style.textContent = `.experience-heading-v2{max-width:720px}.experience-grid-v2{width:min(1050px,100%);margin:38px auto 0;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.experience-card-v2{min-width:0;background:#fff;border:1px solid #e5e8eb;border-radius:20px;padding:22px;box-shadow:0 10px 28px rgba(23,37,54,.06);box-sizing:border-box}.experience-card-meta{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.experience-card-meta>span{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#172536;color:#fff;font-size:10px;font-weight:800}.experience-card-meta>b{color:#e27f25;font-size:9px;font-weight:850;letter-spacing:.1em;text-align:right}.experience-card-v2 h3{margin:0 0 10px;color:#172536;font-size:20px;line-height:1.2;letter-spacing:-.025em}.experience-intro{margin:0;color:#66717d;font-size:13px;line-height:1.6}.experience-link-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;margin-top:18px;min-height:42px;padding:0 15px;border-radius:11px;background:#172536;color:#fff;font-size:10px;font-weight:800;text-decoration:none;transition:transform .2s ease,background .2s ease}.experience-link-btn:hover{transform:translateY(-1px);background:#22384f}.experience-link-btn span{color:#e8892d;font-size:14px}@media(max-width:899px){.experience-grid-v2{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:699px){.experience-grid-v2{grid-template-columns:1fr;margin-top:28px;gap:14px}.experience-card-v2{border-radius:17px;padding:18px}.experience-card-meta{margin-bottom:15px}.experience-card-v2 h3{font-size:18px}.experience-intro{font-size:12px}.experience-link-btn{width:100%;margin-top:15px}}`;
  document.head.appendChild(style);
  section.querySelectorAll('.section-heading,.experience-card-v2').forEach(element=>element.classList.add('reveal'));
  const revealExperience=()=>{section.querySelectorAll('.reveal').forEach(element=>{const rect=element.getBoundingClientRect();if(rect.top<window.innerHeight*.96&&rect.bottom>0)element.classList.add('visible')})};
  if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.01,rootMargin:'0px 0px -5% 0px'});section.querySelectorAll('.reveal').forEach(element=>observer.observe(element))}
  revealExperience();
  window.addEventListener('scroll',revealExperience,{passive:true});
})();